/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFL4kcyXQvh6M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFL4kcyXQvh6M= >>
// ----------- >>
public class Luxury extends Auto {
    // ----------- << attribute.annotations@AAAAAAGFMDwXen9KR6A= >>
    // ----------- >>
    private double prezzo;

    public double getPrezzo() {
        return prezzo;
    }

    public void setPrezzo(double prezzo) {
        this.prezzo = prezzo;
    }

// ----------- << class.extras@AAAAAAGFL4kcyXQvh6M= >>
// ----------- >>
}