/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFMB9GcXkCLyI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFMB9GcXkCLyI= >>
// ----------- >>
public enum TipologiaNoleggio {
    CarSharing,
    BrevePeriodo,
    LungoPerido;

// ----------- << enum.extras@AAAAAAGFMB9GcXkCLyI= >>
// ----------- >>
}