/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFL2yNBm/MLC0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFL2yNBm/MLC0= >>
// ----------- >>
public class UtenteVip extends Utente {
    // ----------- << attribute.annotations@AAAAAAGFL208e2/389c= >>
    // ----------- >>
    private Integer idCarta;

    // ----------- << attribute.annotations@AAAAAAGFMEZfc4EGE6U= >>
    // ----------- >>
    private Integer numeroPunti;

    public Integer getIdCarta() {
        return idCarta;
    }

    public Integer getNumeroPunti() {
        return numeroPunti;
    }

    public void setIdCarta(Integer idCarta) {
        this.idCarta = idCarta;
    }

    public void setNumeroPunti(Integer numeroPunti) {
        this.numeroPunti = numeroPunti;
    }

// ----------- << class.extras@AAAAAAGFL2yNBm/MLC0= >>
// ----------- >>
}