/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.autonoleggi.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFL2jBIW8Nk0s= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFL2jBIW8Nk0s= >>
// ----------- >>
public abstract class Auto {
    // ----------- << attribute.annotations@AAAAAAGFL2jiJm83fzg= >>
    // ----------- >>
    private String modello;

    // ----------- << attribute.annotations@AAAAAAGFL2kWRG8+TbM= >>
    // ----------- >>
    private String targa;

    public String getModello() {
        return modello;
    }

    public String getTarga() {
        return targa;
    }

    public void setModello(String modello) {
        this.modello = modello;
    }

    public void setTarga(String targa) {
        this.targa = targa;
    }

// ----------- << class.extras@AAAAAAGFL2jBIW8Nk0s= >>
// ----------- >>
}