/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.autonoleggi.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFMCWNZXnpU+U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFMCWNZXnpU+U= >>
// ----------- >>
public class Noleggio {
    // ----------- << attribute.annotations@AAAAAAGFMCaVWnqY5vs= >>
    // ----------- >>
    private double prezzo;

    // ----------- << attribute.annotations@AAAAAAGFMCn3jnxLZxQ= >>
    // ----------- >>
    private Integer idNoleggio;

    public double getPrezzo() {
        return prezzo;
    }

    public Integer getIdNoleggio() {
        return idNoleggio;
    }

    public void setPrezzo(double prezzo) {
        this.prezzo = prezzo;
    }

    public void setIdNoleggio(Integer idNoleggio) {
        this.idNoleggio = idNoleggio;
    }

    // ----------- << method.annotations@AAAAAAGFMCjhN3vJgWM= >>
    // ----------- >>
    public double calcolaPrezzo() {
		return 0;
	}
// ----------- << class.extras@AAAAAAGFMCWNZXnpU+U= >>
// ----------- >>
}