/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.autonoleggi.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFL2um8G+JX1Y= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFL2um8G+JX1Y= >>
// ----------- >>
public abstract class Utente {
    // ----------- << attribute.annotations@AAAAAAGFL2wIMG+2TOE= >>
    // ----------- >>
    private String nome;

    // ----------- << attribute.annotations@AAAAAAGFL2woLm+94Po= >>
    // ----------- >>
    private String cognome;

    // ----------- << attribute.annotations@AAAAAAGFL2xKg2/EpAQ= >>
    // ----------- >>
    private Integer id;
    private Integer eta;

    // ----------- << attribute.annotations@AAAAAAGFMA8v63R+jqc= >>
    // ----------- >>
    private Set<Auto> auto = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGFMDHRa32AB5k= >>
    // ----------- >>
    private Set<Noleggio> noleggi = new HashSet<>();

    public String getNome() {
        return nome;
    }

    public String getCognome() {
        return cognome;
    }

    public Integer getId() {
        return id;
    }

 

    public Integer getEta() {
        return eta;
    }

    public Set<Auto> getAuto() {
        return auto;
    }

    public Set<Noleggio> getNoleggi() {
        return noleggi;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setEta(Integer eta) {
        this.eta = eta;
    }


}