/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.autonoleggi.entities;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFL4ih83O4hWg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFL4ih83O4hWg= >>
// ----------- >>
public class Utilitaria extends Auto {
    // ----------- << attribute.annotations@AAAAAAGFMDwtb3+Snko= >>
    // ----------- >>
    private double prezzo;

    public double getPrezzo() {
        return prezzo;
    }

    public void setPrezzo(double prezzo) {
        this.prezzo = prezzo;
    }

// ----------- << class.extras@AAAAAAGFL4ih83O4hWg= >>
// ----------- >>
}